#!/bin/bash

set -e

if [ "$1" = configure ]; then

		INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
		ln -f -s /usr/share/jingyue_control/jingyue_control /usr/bin/jingyue_control

		if [ "systemd" == "$INITSYS" ]; then

			if [ -e /etc/systemd/system/jingyue_control.service ]; then
				rm /etc/systemd/system/jingyue_control.service /usr/lib/systemd/system/jingyue_control.service /usr/lib/systemd/user/jingyue_control.service >/dev/null  2>&1
			fi
			mkdir -p /usr/lib/systemd/system/
			cp /usr/share/jingyue_control/files/systemd/jingyue_control.service /usr/lib/systemd/system/jingyue_control.service
			# try fix error in Ubuntu 18.04
			# Failed to reload jingyue_control.service: Unit jingyue_control.service is not loaded properly: Exec format error.
			# /usr/lib/systemd/system/jingyue_control.service:10: Executable path is not absolute: pkill -f "jingyue_control --"
			if [ -e /usr/bin/pkill ]; then
				sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/jingyue_control.service
			fi
			systemctl daemon-reload
			systemctl enable jingyue_control
			systemctl start jingyue_control
		fi
fi