#!/bin/bash

set -e

case $1 in
    remove|upgrade)
			INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
			rm -f /usr/bin/jingyue_control

			if [ "systemd" == "${INITSYS}" ]; then

				systemctl stop jingyue_control || true
				systemctl disable jingyue_control || true
				rm /etc/systemd/system/jingyue_control.service /usr/lib/systemd/system/jingyue_control.service || true

				# workaround temp dev build between 1.1.9 and 1.2.0
				serverUser=$(ps -ef | grep -E 'jingyue_control +--server' | grep -v 'sudo ' | awk '{print $1}' | head -1)
				if [ "$serverUser" != "" ] && [ "$serverUser" != "root" ]
				then
					systemctl --machine=${serverUser}@.host --user stop jingyue_control >/dev/null 2>&1 || true
				fi
				rm /usr/lib/systemd/user/jingyue_control.service >/dev/null 2>&1 || true
			fi
        ;;
esac

exit 0